apiVersion: apps/v1
kind: Deployment
metadata:
 name: subtract
 labels:
   app: subtract
spec:
 selector:
   matchLabels:
     app: subtract
 replicas: 1
 template:
   metadata:
     labels:
       app: subtract
   spec:
     containers:
     - name: subtract
       image: acr01mcrsvc.azurecr.io/subtractapi:latest
       resources:
         requests:
           cpu: 100m
           memory: 100Mi
         limits:
           cpu: 200m
           memory: 200Mi
       ports:
       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: subtract
spec:
 ports:
 - port: 80
 selector:
   app: subtract
---