apiVersion: apps/v1
kind: Deployment
metadata:
 name: math
 labels:
   app: math
spec:
 selector:
   matchLabels:
     app: math
 replicas: 1
 template:
   metadata:
     labels:
       app: math
   spec:
     containers:
     - name: math
       image: acr01mcrsvc.azurecr.io/mathapi:latest
       resources:
         requests:
           cpu: 100m
           memory: 100Mi
         limits:
           cpu: 200m
           memory: 200Mi
       ports:
       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: math
spec:
 type: LoadBalancer
 ports:
 - port: 80
 selector:
   app: math
---